package io.canduer.nexusflow.service.Impl;

import io.canduer.nexusflow.entity.Customer;
import io.canduer.nexusflow.entity.Invoice;
import io.canduer.nexusflow.service.InvoicePdfService;
import org.openpdf.text.*;
import org.openpdf.text.pdf.PdfWriter;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;

@Service
public class InvoicePdfServiceImpl implements InvoicePdfService {

    @Override
    public byte[] generateInvoicePdf(Invoice invoice) {

        try (ByteArrayOutputStream outputStream = new ByteArrayOutputStream()) {

            Document document = new Document(PageSize.A4);

            PdfWriter.getInstance(document, outputStream);

            document.open();

            addTitle(document);

            addInvoiceInfo(document, invoice);

            addCustomerInfo(document, invoice);

            addInvoiceDetails(document, invoice);

            addFooter(document);

            document.close();

            return outputStream.toByteArray();

        } catch (Exception e) {
            throw new RuntimeException("Failed to generate invoice pdf", e);
        }
    }

    private void addTitle(Document document) throws DocumentException {

        Font title =
                FontFactory.getFont(FontFactory.HELVETICA_BOLD, 22);

        Paragraph heading =
                new Paragraph("NEXUSFLOW", title);

        heading.setAlignment(Element.ALIGN_CENTER);

        document.add(heading);

        Paragraph invoice =
                new Paragraph("INVOICE");

        invoice.setAlignment(Element.ALIGN_CENTER);

        document.add(invoice);

        document.add(Chunk.NEWLINE);
    }

    private void addInvoiceInfo(
            Document document,
            Invoice invoice) throws DocumentException {

        document.add(new Paragraph(
                "Invoice Number : " + invoice.getInvoiceNumber()));

        document.add(new Paragraph(
                "Status : " + invoice.getStatus()));

        document.add(new Paragraph(
                "Invoice Date : " + invoice.getInvoiceDate()));

        document.add(new Paragraph(
                "Due Date : " + invoice.getDueDate()));

        document.add(Chunk.NEWLINE);
    }

    private void addCustomerInfo(
            Document document,
            Invoice invoice) throws DocumentException {

        Customer customer = invoice.getCustomer();

        document.add(new Paragraph("Bill To"));

        document.add(new Paragraph(customer.getName()));

        document.add(new Paragraph(customer.getEmail()));

        document.add(new Paragraph(customer.getAddress()));

        document.add(Chunk.NEWLINE);
    }

    private void addInvoiceDetails(
            Document document,
            Invoice invoice) throws DocumentException {

        document.add(new Paragraph(
                "Service : " + invoice.getServices()));

        document.add(new Paragraph(
                "Total : ₹" + invoice.getTotal()));

        document.add(Chunk.NEWLINE);
    }

    private void addFooter(Document document)
            throws DocumentException {

        document.add(new Paragraph(
                "--------------------------------------------"));

        document.add(new Paragraph(
                "Thank you for doing business with us."));

        document.add(new Paragraph(
                "Generated by NexusFlow"));
    }
}