spring.application.name=nexusflow
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.url=jdbc:h2:mem:securecapita
#spring.datasource.username=aditya
#spring.datasource.password=

#DOCKER postgress container
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://postgres:5432/nexusflow
spring.datasource.username=admin
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update


logging.level.org.springframework.security=DEBUG
jwt.secret=U3VwZXJDYWxpRnJhZ2lsaXN0aWNFeHBpYWxpRG9jaW91czEyMzQ1Njc4OQ==

spring.flyway.baseline-on-migrate=true

#redis properties
spring.data.redis.host=redis
spring.data.redis.port=6379

#kafka
spring.kafka.listener.auto-startup=false
spring.kafka.bootstrap-servers=kafka:9092

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer

spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer

spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

spring.kafka.consumer.properties.spring.json.trusted.packages=*