name: NexusFlow Backend CI

on:
  push:
    branches:
      - master    # Use 'main' if that's your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Show Files
        run: ls -la

      - name: Show Current Directory
        run: pwd